import Head from "next/head";
import AppLayout from "components/AppLayout";
import TrendingSection from "components/Home/TrendingSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <TrendingSection />
      </AppLayout>
    </>
  );
}
