import Head from "next/head";
import Image from "next/image";
import AppLayout from "components/AppLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <h1>Página Home</h1>
      </AppLayout>
    </>
  );
}
